"""empty message

Revision ID: 4d3db79640c9
Revises: e1bd94980514
Create Date: 2020-04-29 15:21:27.298109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d3db79640c9'
down_revision = 'e1bd94980514'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('food_type', sa.Column('is_hidden', sa.Boolean(), nullable=True))
    op.add_column('food_type', sa.Column('in_statistics', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###
    op.execute("UPDATE food_type SET is_hidden = false")
    op.execute("UPDATE food_type SET in_statistics = true")
    op.alter_column('food_type', 'is_hidden', nullable=False)
    op.alter_column('food_type', 'in_statistics', nullable=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('food_type', 'in_statistics')
    op.drop_column('food_type', 'hidden')
    # ### end Alembic commands ###
