"""empty message

Revision ID: e1bd94980514
Revises: 1e175859da76
Create Date: 2020-04-28 21:47:04.266639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1bd94980514'
down_revision = '1e175859da76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('food_type_label_key', 'food_type', type_='unique')
    op.drop_constraint('guinea_pig_name_key', 'guinea_pig', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('guinea_pig_name_key', 'guinea_pig', ['name'])
    op.create_unique_constraint('food_type_label_key', 'food_type', ['label'])
    # ### end Alembic commands ###
